### PR TITLE
Adding buffered crossbar

### PR DESCRIPTION
**Pull request by dpetrisko**
## Summary
This PR adds a new module, bp_me_stream_xbar_buffered, which wraps the xbar with twofers to break timing paths.

## Issue Fixed
This fixes the timing regression from #915, at the cost of additional buffers in the crossbar. 

## Area
The crossbars in bp_tile and bp_unicore_lite, notably the paths to/from the stream pumps.

## Reasoning (outdated, confusing, verbose, etc.)
While buffers are not functionally required, even for helpfulness, a medium-sized crossbar will require these fifos. Additionally, in the unicore these paths include I/O paths, which can be severely late-arriving.

## Analysis
Increased area and 2 additional cycles to L1 cache fill.

## Verification
Normal regression, as this is not a functional change.

### CODE REVIEW

**Review by muwyse — APPROVED** [review]
LGTM!
